server {
    listen 80;
    server_name _;

    # เสิร์ฟไฟล์ React (Frontend)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # ซ้อน Backend (Reverse Proxy)
    location /api/ {
        # เปลี่ยน url ด้านล่างให้ตรงกับชื่อ Service Backend และ Port ใน Railway ของคุณ
        proxy_pass http://todo-back.railway.internal:8080/;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
